### PR TITLE
heroku/maven libcnb.rs rewrite

### LINKED ISSUE #271: maven buildpack: web process picks up source jar
If the project has source/docs the maven buildpack will compile all targets and sometimes picks the wrong jar in the `web` process.

```
Processes:
  TYPE                 SHELL        COMMAND        ARGS
  web (default)        bash         java -Dserver.port=$PORT $JAVA_OPTS -jar target/foo-sources.jar
```

### PR DESCRIPTION
**Pull request by Malax**
This PR is a rewrite of the existing Maven buildpack in Rust with libcnb.rs.  It contains some small improvements over the bash version, but tries to not stray too far from the base implementation. Larger improvements that are now possible with Rust and libcnb.rs will be made in subsequent pull-requests.

## Tests

This PR deliberately doesn't replace the existing Cutlass integration tests. While we certainly want to migrate to `libcnb-test`, the existing tests act as a failsafe to ensure compatibility between the existing bash buildpack and this new one. Minor changes to the existing tests have been made, mostly around logging style which is now governed by libherokubuildpack.

Porting the integration tests from Cutlass to `libcnb-test` will be done as a follow-up PR.

Closes GUS-W-10853677, Closes #271

### CODE REVIEW

File: buildpacks/maven/src/main.rs [hunk 1]
```diff
@@ -0,0 +1,290 @@
...
+            )?;
+
+        let mut maven_options = context
+            .platform
+            .env()
+            .get("MAVEN_CUSTOM_OPTS")
+            .map_or_else(
+                || Ok(default_maven_opts()),
+                |maven_custom_opts_string| {
+                    // Since this is a single environment variable, when users want to add multiple
```
Comment (doriskwan) [inline buildpacks/maven/src/main.rs:192]: This is a single environment variable, therefore whenever users would want to have multiple
options, they would expect it to be split like a UNIX shell would. 
To mimic this behavior, we need to support proper escaping for options that contain spaces.

File: buildpacks/maven/src/main.rs [hunk 2]
```diff
@@ -0,0 +1,290 @@
...
+            .map_err(MavenBuildpackError::SettingsError)?;
+
+        if let Some(settings_xml_path) = settings_xml_path {
+            maven_options.push(String::from("-s"));
+            maven_options.push(settings_xml_path.to_string_lossy().to_string());
+        }
+
+        // We need to set some options that relate to buildpack implementation internals. Those
+        // options must not be overridden by the user via MAVEN_CUSTOM_OPTS for the buildpack to
+        // work correctly. We also don't want to show them when we log the Maven command we're
```
Comment (doriskwan) [inline buildpacks/maven/src/main.rs:210]: To avoid confusion, we won't show the users the logs of the Maven command we are running.

**Review by doriskwan — COMMENTED** [review]
Just some comments on your comments! :)

**Review by edmorley — APPROVED** [review]
